name: "Build Unlocked Test Package"
description: "Create a 2GP beta test package and store its id in a commit status"
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sf-version:
    description: 'version of sf to install'
    required: false
  dev-hub-auth-url:
    description: 'sf auth URL for the Dev Hub'
    required: true
  org-name:
    description: 'Name of the scratch org config to use'
    required: true
    default: dev
runs:
  using: "composite"
  steps:
    - uses: MyClubHub/cumulusci-run-flow-scratch@v4
      with:
        dev-hub-auth-url: '${{ inputs.dev-hub-auth-url }}'
        org-name: '${{ inputs.org-name }}'
        cumulusci-version: '${{ inputs.cumulusci-version }}'
        sf-version: '${{ inputs.sf-version }}'
        flow-name: build_unlocked_test_package
        commit-status-name: "Build Unlocked Test Package"
        commit-status-regex: "04t[a-zA-Z0-9]*"
        commit-status-description-prefix: "version_id: "
